### ISSUE TITLE
 URL Bar Doesn't Update on Tab Switch

### ISSUE THREAD

**Issue by sesawan** [SHAYKHUL/Pysurf#3]
When switching between tabs, the URL bar (`QLineEdit`) does not update to reflect the current tab's URL. This can cause confusion, as the user may think they are still on the previous tab.

**Steps to Reproduce**:
1. Open multiple tabs with different websites.
2. Switch between tabs.
3. Notice that the URL bar does not reflect the current tab's URL.

**Expected Behavior**:  
The URL bar should update to show the current URL of the active tab when switching tabs.

**Proposed Solution**:  
Connect the `currentChanged` signal of the `QTabWidget` to update the URL bar with the current tab's URL.

---

**Comment by SHAYKHUL** [comment]
Thank you for submitting your issue. We apologize for the inconvenience. We are working on a fix and hope you will have a better experience next time.
